name: Release Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Artifact Registry
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_GITHUB_SA_CREDENTIALS }}'

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/happn-app/jwt-exporter:${{ github.event.release.tag_name }}
            eu.gcr.io/happn-infra/happn/jwt-exporter:${{ github.event.release.tag_name }}
